web:
    build: docker
    ports:
        - "80:80"
    volumes:
        - ./docker/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
        - .:/var/www/html/
    environment:
        - ALLOW_OVERRIDE=true
